### ISSUE TITLE
Lien slack

### ISSUE THREAD

**Issue by kud** [francejs/slack#3]
Coucou,

J'ai l'impression que http://slack-francejs.now.sh/ ne fonctionne plus… ?

**Comment by revolunet** [comment]
Hello :) c'est une instance now.sh (v1) ca peut mettre quelques longues secondes avant de démarrer

**Comment by kud** [comment]
Oh okay ! merci :) Effectivement :)

**Comment by caarmen** [comment]
![62F0A8BA-3AC2-4A41-B32A-9020A3714F03](https://user-images.githubusercontent.com/1731388/186758947-98655c32-f1f1-49e6-be33-e48b5d933197.png)

Est-ce que ce slack existe encore? 🤔

**Comment by caarmen** [comment]
J’ai trouvé un nouveau lien ! 🎉 

http://francejs-slack.herokuapp.com/

**Comment by revolunet** [comment]
merci j'ai modifié le readme
